### ISSUE TITLE
AttributeError: 'module' object has no attribute 'CodeView'

### ISSUE THREAD

**Issue by djowett** [miohtama/visualtitle#3]
I get the following error on install, (Plone 4.3.2).

```
Traceback (most recent call last):
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/__init__.py", line 47, in startup
    _startup()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/App/startup.py", line 118, in startup
    load_zcml()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/App/startup.py", line 52, in load_zcml
    load_site()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Zope2-2.13.21-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/z3c.autoinclude-0.3.4-py2.7.egg/z3c/autoinclude/zcml.py", line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/z3c.autoinclude-0.3.4-py2.7.egg/z3c/autoinclude/zcml.py", line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/daniel/dev/Plone/Development/Python-2.7.5/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/grokcore.component-2.5-py2.7.egg/grokcore/component/zcml.py", line 57, in grokDirective
    do_grok(package.__name__, _context, extra_exclude=exclude)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/grokcore.component-2.5-py2.7.egg/grokcore/component/zcml.py", line 71, in do_grok
    config=config)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 203, in grok_dotted_name
    grok_package(module_info, grokker, **kw)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 208, in grok_package
    grok_package(sub_module_info, grokker, **kw)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 206, in grok_package
    grok_module(module_info, grokker, **kw)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/core.py", line 211, in grok_module
    grokker.grok(module_info.dotted_name, module_info.getModule(),
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/scan.py", line 141, in getModule
    self._module = resolve(self.dotted_name)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/martian-0.14-py2.7.egg/martian/scan.py", line 217, in resolve
    __import__(used)
  File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/visualtitle-0.2.2-py2.7.egg/visualtitle/views.py", line 21, in <module>
    class VisualTitle(grok.CodeView):
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/daniel/dev/Plone/Development/bbk4/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/Products.CMFPlone-4.3.2-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/home/daniel/dev/Plone/Development/buildout-cache/eggs/visualtitle-0.2.2-py2.7.egg/visualtitle/configure.zcml", line 15.2-15.27
    AttributeError: 'module' object has no attribute 'CodeView'
```

Looking at similar issues online it would seem the fix is to change

```
class VisualTitle(grok.CodeView):
```

to

```
class FixBlobs(grok.View):
```

In visualtitle/views.py", at line 21.   I will try it & let you know.

**Comment by djowett** [comment]
Fixed by above pull request
